version: '3.8'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db-data:/var/lib/postgresql/data/
    env_file:
      - .env
  web:
    image: martiarti/api_yamdb:v1.0
    command: >
      sh -c "python manage.py migrate &&
             python manage.py loaddata fixtures.json &&
             gunicorn api_yamdb.wsgi:application --bind 0:8000"
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - .env
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
volumes:
  static_value:
  media_value:
  db-data:
