# Generated by Django 3.2 on 2022-12-18 22:24

import reviews.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20221218_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, validators=[reviews.validators.validate_username], verbose_name='Имя пользователя'),
        ),
    ]
